### ISSUE TITLE
Plugins must be defined under a specific namespace

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hydra_plugins_wg#26]
**Rationale:** having a convention around plugin namespaces:
  * can alleviate bugs that may arise from potential namespace collisions
  * adds more predictability for where modules, classes, and files live.
  * provides a convenient space for defining common plugin code.

**Done when:** guideline is accepted or rejected

**Comment by afred** [comment]
@projecthydra-labs/hydra_plugins_wg so, as per our meeting, we were wondering which would be a better namespace....

  * `Hyrax::YourPluginHere`
  * `Hyrax::Plugins::YourPluginHere`

please take a minute and give a 👍 or 👎 on one of these. Thanks!

**Comment by botimer** [comment]
I don't see a lot of value in an arbitrary/empty layer. That is, `Hyrax::AwesomeThing` seems fine to me. If there would be collisions at that level (with something in the core), it would probably be a confusing plugin name at either level. Two plugins colliding would also not be solved by another level, so that will be a "plugin index/registry" concern.

As far as knowing whether something comes from a plugin or not, I don't think the namespace layer helps there, either. I think having a consistent place to put plugins on disk and a way to interrogate a running system is totally sufficient.

**Comment by mbarnett** [comment]
👍 Hyrax::YourPluginHere, although it's a weak preference and I'm fine with other

**Comment by afred** [comment]
@botimer I'm more concerned about namespace collisions going the other way. For instance

1. Say I'm using a plugin called `Hyrax::Media`, which might provide data modeling and workflow for audio/video materials.
1. Say the latest release of Hyrax includes a module or class called`Hyrax::Media` for some other purpose.
1. My app will break when I upgrade.

The intermediary namespace helps to avoid getting in the way of core development. As discussed in the meeting, we could have some conventional naming, such as suffixing all plugin names with the word "plugin", so it would become `Hyrax::MediaPlugin`, but I think that is a little clunky.

**Comment by botimer** [comment]
@afred Ahh yes -- this is persuasive. `Hyrax::Plugin::Xyz` works for me.

**Comment by afred** [comment]
Rethinking a bit. I can see where we'll probably come up with something like `Hyrax::Plugins` as a namespace for the plugin interface for Hyrax.

However, do plugins themselves need to live under `Hyrax` namespace at all?

I now realize that top-level namespacing of plugins wasn't on the agenda for discussion. My bad.
