### ISSUE TITLE
Plugins should not monkey patch classes from other gems

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hydra_plugins_wg#31]
**Rationale:** Monkey patching classes or modules from other gems changes the interface of those gems. This can lead to errors for consumers of the monkey patched gems, which may be the host application, or other gems.

**Guideline:** Plugins **should not** monkey patch classes or modules from other gems, or classes or modules that are generated into the host application.

**Done when:**
  - [ ] provide a context for what we mean by "monkey patching"
  - [ ] this guideline is accepted, or rejected.

**Comment by afred** [comment]
@projecthydra-labs/hydra_plugins_wg

**Comment by jcoyne** [comment]
I don't think that the scope of "monkey patching" is well understood. Would you care to define exactly what you mean?

**Comment by afred** [comment]
Opening up an existing class or module and changing the behavior of a method. That includes method signature, return value, or side effects.

**Comment by jcoyne** [comment]
@afred how about `OtherClass.include NewBehavior`?  I could use that to do most of those things without "opening it up"

**Comment by botimer** [comment]
My opinion on this is that the need or desire to mix in behavior from the outside should instead open the conversation of how to make an extension point for the need.

Granted, there may be times where the "core" code is far from a new release that a plugin wants to target. It may be necessary for a time.

My general point is that this is rightly in the "should" space. Mixins (whatever the syntax/convenience is) "should not" be the preferred way to extend behavior, especially across gems. It changes stuff that "isn't yours" in an implicit (to everyone else) way.

**Comment by botimer** [comment]
I suppose I should also say... there are times when a component should allow additional capabilities to be added to it. A classic example is a serializer. Support for additional formats might be added via plugin.

This could be done by a mixin (and maybe conventional method names for the specific formats). It could also be done by exposing a method to register a format/formatter.

I strongly prefer the latter as a purpose-specific extension point. The design expressly denotes that there are collaborators for specific formats, rather than the much looser design contract of encouraging mixins.

**Comment by jcoyne** [comment]
Yes. I agree. I just think we should use clearly understood language. I don't think "monkey patch" is well defined

**Comment by botimer** [comment]
Okay, nice. Do you think something generic like "modify classes or modules" is clear enough? We could give a couple of examples like: (as by reopening a class to override a method or mixing in modules).

Does that cover it without leaving a definition to the reader?
